let data=[],selectedIds=new Set(),lastClickedIndex=null;
const $=id=>document.getElementById(id),container=$("cardContainer"),searchInput=$("searchInput"),resultCount=$("resultCount"),copyBtn=$("copyBtn"),clearBtn=$("clearBtn"),copiedMsg=$("copiedMsg"),clearSearchBtn=$("clearSearchBtn"),filtersRoot=$("filtersRoot"),emptyState=$("emptyState"),sidebarToggle=$("sidebarToggle"),sidebarBackdrop=$("sidebarBackdrop"),appRoot=document.querySelector(".app");
const getVal=(obj,path)=>path.split(".").reduce((o,k)=>o?.[k],obj); const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const activeFilterValues={};
fetch(AppConfig.dataUrl).then(r=>r.json()).then(json=>{data=json;buildFilterSections();render()}).catch(()=>{emptyState.hidden=false;emptyState.textContent="Unable to load contacts."});
function buildFilterSections(){filtersRoot.innerHTML="";AppConfig.filters.forEach(fd=>{activeFilterValues[fd.key]=new Set();const section=document.createElement("section");section.className="filter-section";section.innerHTML=`<h4>${esc(fd.label)}</h4><input class="filter-search" placeholder="${esc(fd.searchPlaceholder)}"><div class="filter-list pills"></div>`;const pills=section.querySelector(".pills"),values=[...new Set(data.map(d=>getVal(d,fd.key)).filter(Boolean))].sort((a,b)=>{if(!fd.sortOrder)return a.localeCompare(b);return (fd.sortOrder.indexOf(a)+99)%99-(fd.sortOrder.indexOf(b)+99)%99});values.forEach(v=>{const label=document.createElement("label");label.className="pill";label.innerHTML=`<input type="checkbox" value="${esc(v)}"> ${esc(v)}`;label.addEventListener("change",e=>{e.target.checked?activeFilterValues[fd.key].add(v):activeFilterValues[fd.key].delete(v);label.classList.toggle("active",e.target.checked);render()});pills.append(label)});section.querySelector("input.filter-search").addEventListener("input",e=>pills.querySelectorAll(".pill").forEach(p=>p.hidden=!p.textContent.toLowerCase().includes(e.target.value.toLowerCase())));filtersRoot.append(section)})}
function getFilteredData(){const term=searchInput.value.trim().toLowerCase();return data.filter(item=>(!term||AppConfig.searchFields.some(f=>String(getVal(item,f)??"").toLowerCase().includes(term)))&&AppConfig.filters.every(fd=>!activeFilterValues[fd.key].size||activeFilterValues[fd.key].has(getVal(item,fd.key))))}
function render(){const filtered=getFilteredData();resultCount.textContent=`${filtered.length} results`;container.innerHTML="";emptyState.hidden=!!filtered.length;filtered.forEach((item,index)=>container.append(buildCard(item,index)))}
function buildCard(item,index){const id=getVal(item,AppConfig.idField),cfg=AppConfig.card,card=document.createElement("article");card.className=`card ${selectedIds.has(id)?"selected":""}`;const initials=(getVal(item,cfg.avatarField)||"").split(" ").map(x=>x[0]).join("");const rows=cfg.rows.map(row=>{const val=getVal(item,row.field);if(!val)return"";if(row.type==="phone"){const d=String(val).replace(/\D/g,"");return `<div class="meta"><i class="${row.icon}"></i><a href="tel:${d}">${esc(val)}</a>${row.whatsapp?`<a class="whatsapp" href="https://wa.me/${d}" target="_blank" rel="noopener" aria-label="WhatsApp"><i class="fa-brands fa-whatsapp"></i></a>`:""}</div>`}return `<div class="meta ${row.copy?"email-row":""}"><i class="${row.icon}"></i><span>${esc(val)}</span>${row.copy?`<button class="copy-icon" data-copy="${esc(val)}" aria-label="Copy email"><i class="fa-regular fa-copy"></i></button>`:""}</div>`}).join("");card.innerHTML=`<input class="select-box" type="checkbox" ${selectedIds.has(id)?"checked":""} aria-label="Select ${esc(getVal(item,cfg.titleField))}"><div class="avatar">${esc(initials)}</div><div class="name">${esc(getVal(item,cfg.titleField))}</div><div class="designation">${esc(getVal(item,cfg.subtitleField))}</div>${rows}<button class="history-action" type="button"><i class="fa-solid fa-clock-rotate-left"></i> View history</button>`;card.addEventListener("click",e=>{if(e.target.closest("a,button,input"))return;toggleSelection(id,index,e.shiftKey)});card.querySelector(".select-box").addEventListener("change",e=>toggleSelection(id,index,e.shiftKey));card.querySelector(".copy-icon")?.addEventListener("click",e=>{navigator.clipboard.writeText(e.currentTarget.dataset.copy);showCopied()});card.querySelector(".history-action").addEventListener("click",e=>{e.stopPropagation();HistoryTimeline.open(item,e.currentTarget)});return card}
function toggleSelection(id,index,shift){const filtered=getFilteredData();if(shift&&lastClickedIndex!==null){for(let i=Math.min(index,lastClickedIndex);i<=Math.max(index,lastClickedIndex);i++)selectedIds.add(getVal(filtered[i],AppConfig.idField))}else selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);lastClickedIndex=index;render()}
function showCopied(){copiedMsg.style.display="block";setTimeout(()=>copiedMsg.style.display="none",1200)}
copyBtn.addEventListener("click",()=>{const emails=data.filter(i=>selectedIds.has(getVal(i,AppConfig.idField))).map(i=>getVal(i,"officer.email")).filter(Boolean);if(emails.length){navigator.clipboard.writeText(emails.join(", "));showCopied()}});clearBtn.addEventListener("click",()=>{selectedIds.clear();render()});searchInput.addEventListener("input",()=>{clearSearchBtn.hidden=!searchInput.value;render()});clearSearchBtn.addEventListener("click",()=>{searchInput.value="";clearSearchBtn.hidden=true;render();searchInput.focus()});sidebarToggle.addEventListener("click",()=>{appRoot.classList.toggle("sidebar-open");sidebarBackdrop.classList.toggle("show")});sidebarBackdrop.addEventListener("click",()=>{appRoot.classList.remove("sidebar-open");sidebarBackdrop.classList.remove("show")});document.addEventListener("keydown",e=>{if(e.key==="Escape"){appRoot.classList.remove("sidebar-open");sidebarBackdrop.classList.remove("show")}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="a"&&document.activeElement===searchInput){e.preventDefault();getFilteredData().forEach(i=>selectedIds.add(getVal(i,AppConfig.idField)));render()}});
