const AppConfig = {
    dataUrl: "contacts.json",

    // Stable ID generated by transformData.py. Falls back in app.js if absent.
    idField: "id",

    // Fields included in global search. Empty/missing fields are ignored.
    searchFields: [
        "officer.name",
        "officer.pinNumber",
        "officer.email",
        "officer.primaryPhone",
        "officer.mobile", // legacy contacts.json compatibility
        "officer.designation",
        "officeName",
        "section",
        "zone",
        "circle",
        "division",
        "category",
        "subCategory",
        "status"
    ],

    // Maps canonical circles to parent zones for the Zone -> Circle cascade.
    circleToZone: {
        "BANGALORE NORTH": "BMAZ NORTH",
        "BANGALORE EAST": "BMAZ NORTH",
        "BANGALORE CENTRAL": "BMAZ NORTH",
        "BANGALORE WEST": "BMAZ SOUTH",
        "BANGALORE SOUTH": "BMAZ SOUTH",
        "RAMANAGAR": "BRAZ",
        "BANGALORE RURAL": "BRAZ",
        "KOLAR": "BRAZ",
        "DAVANAGERE": "CTAZ",
        "TUMKUR": "CTAZ"
    },

    // Sidebar facets. Division/subdivision are deliberately excluded for now.
    filters: [
        {
            key: "zone",
            label: "Zone",
            search: false,
            sortOrder: ["BMAZ NORTH", "BMAZ SOUTH", "BRAZ", "CTAZ"]
        },
        {
            key: "circle",
            label: "Circle",
            searchPlaceholder: "Search circle...",
            cascadeFrom: "zone",
            parentMap: "circleToZone",
            sortOrder: [
                "BANGALORE NORTH",
                "BANGALORE EAST",
                "BANGALORE CENTRAL",
                "BANGALORE WEST",
                "BANGALORE SOUTH",
                "RAMANAGAR",
                "BANGALORE RURAL",
                "KOLAR",
                "DAVANAGERE",
                "TUMKUR"
            ]
        },
        {
            key: "category",
            label: "Category",
            search: false,
            sortOrder: ["Engineer", "Accounts", "Corporate Office"]
        },
        {
            key: "status",
            label: "Status",
            search: false,
            sortOrder: ["Active", "Vacant"]
        },
        {
            // Corporate Office records use AGM/DGM/GM/CGM/etc.; field records use full designation.
            key: "displayDesignation",
            label: "Designation / Rank",
            searchPlaceholder: "Search designation or rank...",
            value: item => item.subCategory || item.officer?.designation,
            sortOrder: [
                "Assistant Executive Engineer (Ele)",
                "Assistant Executive Engineer (Civil)",
                "Executive Engineer (Ele)",
                "Executive Engineer (Civil)",
                "Superintending Engineers(Ele)",
                "Chief Engineer (Ele)",
                "Accounts Officers",
                "Deputy Controller of Accounts",
                "Chief Controllers of Accouts",
                "AGM",
                "DGM",
                "GM",
                "CGM",
                "Company Secretary",
                "Director",
                "Other"
            ]
        }
    ],

    // Cards omit a row completely when its field/fallback field is empty.
    card: {
        avatarField: "officer.name",
        titleField: "officer.name",
        subtitleField: "officer.designation",
        statusField: "status",
        badgeField: "subCategory",
        rows: [
            { icon: "fa-solid fa-building", field: "officeName" },
            { icon: "fa-solid fa-location-dot", fields: ["zone", "circle", "division"], separator: " • ", fallbackField: "category" },
            { icon: "fa-solid fa-envelope", field: "officer.email", type: "email", copy: true },
            {
                icon: "fa-solid fa-phone",
                field: "officer.primaryPhone",
                fallbackField: "officer.mobile",
                type: "phone",
                copy: true,
                whatsapp: true
            },
            {
    icon: "fa-solid fa-calendar-days",
    value: item => {
        const raw = item.dateOfAssumingCharge;
        if (!raw) return "";
        const date = new Date(raw);
        const formatted = date.toLocaleDateString("en-IN", {
            day: "2-digit", month: "short", year: "numeric"
        });
        const diffDays = Math.floor((new Date() - date) / 86400000);
        const years = Math.floor(diffDays / 365);
        const months = Math.floor((diffDays % 365) / 30);
        let duration = years > 0 ? `${years} yr ` : "";
        duration += months > 0 ? `${months} mo` : "";
        if (!duration) duration = `${diffDays} days`;
        return `Assumed charge: ${formatted}  •  ${duration.trim()}`;
    }
}
        ]
    },

    csvExport: {
        filenamePrefix: "bescom_contacts",
        columns: [
            { header: "ID", field: "id" },
            { header: "Name", field: "officer.name" },
            { header: "Designation", field: "officer.designation" },
            { header: "PIN Number", field: "officer.pinNumber" },
            { header: "Email", field: "officer.email" },
            { header: "Primary Phone", field: "officer.primaryPhone", fallbackField: "officer.mobile" },
            { header: "Category", field: "category" },
            { header: "Rank", field: "subCategory" },
            { header: "Status", field: "status" },
            { header: "Office", field: "officeName" },
            { header: "Section", field: "section" },
            { header: "Zone", field: "zone" },
            { header: "Circle", field: "circle" },
            { header: "Division", field: "division" },
            { header: "Date of Assuming Charge", field: "dateOfAssumingCharge" }
        ]
    }
};
